name: Deploy to EC2

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.26.177.199 << 'EOF'
          cd /home/ubuntu/onlineElection  # Replace with your app directory on EC2
          git pull origin main
          # Your build and restart commands below, example:
          # npm install
          # npm run build
          # pm2 restart all
        EOF
